# Generated by Django 3.0.7 on 2020-06-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='image',
            field=models.ImageField(default='', upload_to='consumer/images/'),
        ),
    ]
