# Generated by Django 3.0.6 on 2020-06-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200601_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='importent',
            new_name='important',
        ),
    ]
