# Generated by Django 3.0.5 on 2020-06-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetailapp', '0002_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
